#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#
#  Copyright 2016 Fatih KAYA <sonakinci41@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA


import sys
import os

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

from dbus.mainloop.glib import DBusGMainLoop
import comar
import pisi.api
import pisi.db

from limestorelib import pm, resource


def main():
    uyg = QApplication(sys.argv)
    uyg.setOrganizationName('limelinux-store')
    locale = QLocale.system().name()
    translator = QTranslator(uyg)
    translator.load("diller/{}.qm".format(locale))
    uyg.installTranslator(translator)
    ana = pm.pmMainClass()
    ana.show()
    sys.exit(uyg.exec_())


if __name__ == "__main__":
    main()
